---
title: "ggplot"
output: pdf_document
date: "2024-05-27"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(tidyverse)
```

## Import data

```{r}
str(iris)
summary(iris)
head(iris)
```


```{r}
ggplot(iris) + geom_bar(aes(x=Sepal.Length), stat="bin", binwidth = 3)
```


```{r}
group_iris <- iris %>% group_by(Species) %>% dplyr::summarise(avg_sepal_length=mean(Sepal.Length))
str(group_iris)
p <- ggplot(group_iris) + geom_bar(aes(x=Species, weight=avg_sepal_length, fill=Species))
p
```


```{r}
p <- p + scale_fill_manual(
  values = c("skyblue", "royalblue", "navy"),
  limits = c("setosa", "versicolor", "virginica"), 
  breaks = c("setosa", "versicolor", "virginica"), 
  name = "Species",  
  labels = c("set", "ver", "vir") 
)
p
f.scatter <- ggplot(iris) + geom_point(aes(x=Sepal.Length, y=Sepal.Width, color=Species))
f.scatter
# Boxplot to explore numeric variable
p.box <- ggplot(iris) + geom_boxplot(aes(x=Species, y=Petal.Length))
p.box
# One way we can extend this plot is adding a layer of individual points on top of it
p.box.jitter <- p.box + geom_jitter(aes(x=Species, y=Petal.Length, color=Species))
p.box.jitter
# A final plot useful for looking at univariate relations is the kdeplot,
p.density <- ggplot(iris) + geom_density(aes(x=Petal.Length, colour=Species)) 
p.density
```